version: "3"

services:
  python_load_tester:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/yijunx/code
      - ~/etc/localtime:/opt/yijunx/etc/localtime
      - ~/etc/timezone:/opt/yijunx/etc/timezone
    command: ["tail -f /dev/null"]
    ports:
      - 8000:8000
    networks:
      - default

  resource_app:
    image: yijunx/resource_app:0.0.1
    ports:
      - 5432:8000
    networks:
      - default

networks:
  default:
    external:
      name: micro-services
